# Generated by Django 3.0.2 on 2020-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('website_link', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('college_year', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_customer',
            new_name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
