# Generated by Django 3.0.2 on 2020-01-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200120_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='email_id',
            new_name='email',
        ),
    ]
