# Generated by Django 3.0.2 on 2020-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200120_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='website_link',
            field=models.URLField(),
        ),
    ]
