# Generated by Django 3.0.2 on 2020-02-12 20:51

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_roles', models.TextField(max_length=1000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RegCompany',
            fields=[
                ('id', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('apply_profile', models.ManyToManyField(blank=True, to='company.ApplyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('your_postion', models.CharField(max_length=100, null=True)),
                ('name_of_founders', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('profiles_offered', multiselectfield.db.fields.MultiSelectField(choices=[('w', 'Web Development'), ('a', 'Coding'), ('b', 'Analytics'), ('c', 'Operations'), ('d', 'Business Development'), ('d', 'Design'), ('e', 'Content Development'), ('f', 'Product Development'), ('g', 'Finance'), ('h', 'Sales'), ('i', 'Management Consulting'), ('j', 'Others')], max_length=1000, null=True)),
                ('others', models.CharField(max_length=1000, null=True)),
                ('number_of_vacancies', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=1000, null=True)),
                ('stipend_offered', models.CharField(max_length=1000, null=True)),
                ('work_profile_description', models.CharField(max_length=1000, null=True)),
                ('other_incentive', models.CharField(max_length=1000, null=True)),
                ('requirements', models.CharField(max_length=1000, null=True)),
                ('reference', models.CharField(max_length=1000, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CompanyProfile')),
            ],
        ),
    ]
