# Generated by Django 3.0.2 on 2020-01-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000, null=True)),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('your_postion', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('profiles_offered', multiselectfield.db.fields.MultiSelectField(choices=[('w', 'Web Development'), ('a', 'Coding'), ('b', 'Analytics'), ('c', 'Operations'), ('d', 'Business Development'), ('d', 'Design'), ('e', 'Content Development'), ('f', 'Product Development'), ('g', 'Finance'), ('h', 'Sales'), ('i', 'Management Consulting')], max_length=1000, null=True)),
                ('others', models.CharField(max_length=1000, null=True)),
                ('contact_number', models.IntegerField()),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
